// Cluster taxonomy: slug -> related calculator/guide slugs.
// Single source for the RelatedContent component, so internal linking is
// systematic rather than hand-built per page.
export const relatedMap: Record<string, string[]> = {
  "pro-rata-calculator": [
    "take-home-pay-calculator",
    "holiday-entitlement-calculator",
    "annual-leave-calculator",
    "holiday-entitlement-part-time-workers",
    "nhs-take-home-pay",
  ],
  "take-home-pay-calculator": [
    "net-to-gross-calculator",
    "national-insurance-calculator",
    "two-jobs-tax-calculator",
    "salary-sacrifice-calculator",
    "employer-ni-calculator",
    "employee-cost-calculator",
    "pro-rata-calculator",
    "nhs-take-home-pay",
  ],
  "net-to-gross-calculator": [
    "take-home-pay-calculator",
    "two-jobs-tax-calculator",
    "national-insurance-calculator",
    "employer-ni-calculator",
    "ir35-calculator",
    "salary-sacrifice-calculator",
  ],
  "national-insurance-calculator": [
    "employer-ni-calculator",
    "take-home-pay-calculator",
    "employee-cost-calculator",
    "two-jobs-tax-calculator",
    "workplace-pension-calculator",
    "national-insurance-rates-2026-27",
  ],
  "two-jobs-tax-calculator": [
    "take-home-pay-calculator",
    "net-to-gross-calculator",
    "national-insurance-calculator",
    "employer-ni-calculator",
    "workplace-pension-calculator",
  ],
  "ir35-calculator": [
    "take-home-pay-calculator",
    "net-to-gross-calculator",
    "employer-ni-calculator",
    "employee-cost-calculator",
    "national-insurance-calculator",
  ],
  "employer-ni-calculator": [
    "employee-cost-calculator",
    "national-insurance-calculator",
    "employment-allowance-guide",
    "employer-ni-rates-2026-27",
    "salary-sacrifice-pension-calculator",
    "workplace-pension-calculator",
  ],
  "employee-cost-calculator": [
    "employer-ni-calculator",
    "workplace-pension-calculator",
    "how-much-does-it-cost-to-employ-someone",
    "true-cost-of-hiring-employee-uk",
    "salary-sacrifice-pension-calculator",
    "national-insurance-calculator",
  ],
  "workplace-pension-calculator": [
    "salary-sacrifice-pension-calculator",
    "salary-sacrifice-pension-guide",
    "workplace-pension-contributions-explained",
    "employee-cost-calculator",
    "employer-ni-calculator",
  ],
  "salary-sacrifice-pension-calculator": [
    "workplace-pension-calculator",
    "salary-sacrifice-calculator",
    "salary-sacrifice-pension-guide",
    "employer-ni-calculator",
    "workplace-pension-contributions-explained",
  ],
  "salary-sacrifice-calculator": [
    "salary-sacrifice-pension-calculator",
    "salary-sacrifice-pension-guide",
    "take-home-pay-calculator",
    "workplace-pension-calculator",
    "employer-ni-calculator",
  ],
  "ssp-calculator": [
    "sick-pay-calculator",
    "how-to-calculate-statutory-sick-pay",
    "ssp-vs-company-sick-pay",
    "ssp-changes-april-2026",
    "bradford-factor-calculator",
    "employee-cost-calculator",
  ],
  "sick-pay-calculator": [
    "ssp-calculator",
    "ssp-vs-company-sick-pay",
    "ssp-changes-april-2026",
    "bradford-factor-calculator",
    "how-to-calculate-statutory-sick-pay",
  ],
  "bradford-factor-calculator": [
    "ssp-calculator",
    "sick-pay-calculator",
    "ssp-vs-company-sick-pay",
    "annual-leave-calculator",
    "ssp-changes-april-2026",
  ],
  "smp-calculator": [
    "maternity-allowance-calculator",
    "ssp-calculator",
    "take-home-pay-calculator",
    "employee-cost-calculator",
  ],
  "maternity-allowance-calculator": [
    "smp-calculator",
    "take-home-pay-calculator",
    "national-insurance-calculator",
    "employee-cost-calculator",
  ],
  "annual-leave-calculator": [
    "holiday-entitlement-calculator",
    "statutory-holiday-entitlement-uk",
    "holiday-entitlement-part-time-workers",
    "pro-rata-calculator",
    "bradford-factor-calculator",
  ],
  "holiday-entitlement-calculator": [
    "annual-leave-calculator",
    "statutory-holiday-entitlement-uk",
    "holiday-entitlement-part-time-workers",
    "pro-rata-calculator",
    "employee-cost-calculator",
  ],
  "p11d-calculator": [
    "company-car-tax-calculator",
    "employer-ni-calculator",
    "take-home-pay-calculator",
    "employee-cost-calculator",
  ],
  "company-car-tax-calculator": [
    "p11d-calculator",
    "take-home-pay-calculator",
    "employer-ni-calculator",
    "salary-sacrifice-calculator",
  ],
  "nhs-take-home-pay": [
    "nhs-pay-comparison",
    "nhs-midwife-salary",
    "take-home-pay-calculator",
    "pro-rata-calculator",
    "nhs-band-2-pay-calculator",
    "nhs-band-5-pay-calculator",
    "nhs-band-6-pay-calculator",
    "nhs-band-7-pay-calculator",
    "nhs-band-8a-pay-calculator",
    "nhs-band-9-pay-calculator",
    "nhs-scotland-band-6-pay-calculator",
    "nhs-wales-band-7-pay-calculator",
  ],
  "nhs-pay-comparison": [
    "nhs-take-home-pay",
    "nhs-midwife-salary",
    "take-home-pay-calculator",
    "pro-rata-calculator",
    "nhs-band-5-pay-calculator",
    "nhs-band-6-pay-calculator",
  ],
  "nhs-midwife-salary": [
    "nhs-band-5-pay-calculator",
    "nhs-band-6-pay-calculator",
    "nhs-band-7-pay-calculator",
    "nhs-take-home-pay",
    "nhs-pay-comparison",
  ],
  "employer-ni-rates-2026-27": [
    "employer-ni-calculator",
    "national-insurance-calculator",
    "employment-allowance-guide",
    "national-insurance-rates-2026-27",
    "employee-cost-calculator",
  ],
  "national-insurance-rates-2026-27": [
    "national-insurance-calculator",
    "take-home-pay-calculator",
    "employer-ni-calculator",
    "employer-ni-rates-2026-27",
    "employment-allowance-guide",
  ],
  "statutory-holiday-entitlement-uk": [
    "holiday-entitlement-calculator",
    "annual-leave-calculator",
    "holiday-entitlement-part-time-workers",
    "pro-rata-calculator",
  ],
  "how-to-calculate-statutory-sick-pay": [
    "ssp-calculator",
    "sick-pay-calculator",
    "ssp-vs-company-sick-pay",
    "ssp-changes-april-2026",
    "bradford-factor-calculator",
  ],
  "ssp-vs-company-sick-pay": [
    "ssp-calculator",
    "sick-pay-calculator",
    "how-to-calculate-statutory-sick-pay",
    "ssp-changes-april-2026",
    "bradford-factor-calculator",
    "employee-cost-calculator",
  ],
  "employment-allowance-guide": [
    "employer-ni-calculator",
    "employer-ni-rates-2026-27",
    "employee-cost-calculator",
    "national-insurance-calculator",
  ],
  "how-much-does-it-cost-to-employ-someone": [
    "employee-cost-calculator",
    "employer-ni-calculator",
    "true-cost-of-hiring-employee-uk",
    "workplace-pension-calculator",
    "workplace-pension-contributions-explained",
  ],
  "true-cost-of-hiring-employee-uk": [
    "how-much-does-it-cost-to-employ-someone",
    "employee-cost-calculator",
    "employer-ni-calculator",
    "workplace-pension-calculator",
    "ssp-calculator",
  ],
  "salary-sacrifice-pension-guide": [
    "salary-sacrifice-pension-calculator",
    "salary-sacrifice-calculator",
    "workplace-pension-calculator",
    "workplace-pension-contributions-explained",
    "employer-ni-calculator",
  ],
  "holiday-entitlement-part-time-workers": [
    "holiday-entitlement-calculator",
    "annual-leave-calculator",
    "pro-rata-calculator",
    "statutory-holiday-entitlement-uk",
  ],
  "workplace-pension-contributions-explained": [
    "workplace-pension-calculator",
    "salary-sacrifice-pension-calculator",
    "salary-sacrifice-pension-guide",
    "employer-ni-calculator",
    "employee-cost-calculator",
  ],
  "ssp-changes-april-2026": [
    "ssp-calculator",
    "sick-pay-calculator",
    "how-to-calculate-statutory-sick-pay",
    "ssp-vs-company-sick-pay",
    "employee-cost-calculator",
    "bradford-factor-calculator",
  ],
  "nhs-band-2-pay-calculator": [
    "nhs-band-3-pay-calculator",
    "nhs-take-home-pay",
    "nhs-pay-comparison",
    "nhs-midwife-salary",
    "take-home-pay-calculator",
  ],
  "nhs-band-3-pay-calculator": [
    "nhs-band-2-pay-calculator",
    "nhs-band-4-pay-calculator",
    "nhs-take-home-pay",
    "nhs-pay-comparison",
    "nhs-midwife-salary",
  ],
  "nhs-band-4-pay-calculator": [
    "nhs-band-3-pay-calculator",
    "nhs-band-5-pay-calculator",
    "nhs-take-home-pay",
    "nhs-pay-comparison",
    "nhs-midwife-salary",
  ],
  "nhs-band-5-pay-calculator": [
    "nhs-band-4-pay-calculator",
    "nhs-band-6-pay-calculator",
    "nhs-midwife-salary",
    "nhs-take-home-pay",
    "nhs-pay-comparison",
    "nhs-scotland-band-5-pay-calculator",
    "nhs-wales-band-5-pay-calculator",
  ],
  "nhs-band-6-pay-calculator": [
    "nhs-band-5-pay-calculator",
    "nhs-band-7-pay-calculator",
    "nhs-take-home-pay",
    "nhs-pay-comparison",
    "nhs-scotland-band-6-pay-calculator",
    "nhs-wales-band-6-pay-calculator",
  ],
  "nhs-band-7-pay-calculator": [
    "nhs-band-6-pay-calculator",
    "nhs-band-8a-pay-calculator",
    "nhs-take-home-pay",
    "nhs-pay-comparison",
    "nhs-scotland-band-7-pay-calculator",
    "nhs-wales-band-7-pay-calculator",
  ],
  "nhs-band-8a-pay-calculator": [
    "nhs-band-7-pay-calculator",
    "nhs-band-8b-pay-calculator",
    "nhs-take-home-pay",
    "nhs-pay-comparison",
    "nhs-scotland-band-8a-pay-calculator",
    "nhs-wales-band-8a-pay-calculator",
  ],
  "nhs-band-8b-pay-calculator": [
    "nhs-band-8a-pay-calculator",
    "nhs-band-8c-pay-calculator",
    "nhs-take-home-pay",
    "nhs-pay-comparison",
  ],
  "nhs-band-8c-pay-calculator": [
    "nhs-band-8b-pay-calculator",
    "nhs-band-8d-pay-calculator",
    "nhs-take-home-pay",
    "nhs-pay-comparison",
  ],
  "nhs-band-8d-pay-calculator": [
    "nhs-band-8c-pay-calculator",
    "nhs-band-9-pay-calculator",
    "nhs-take-home-pay",
    "nhs-pay-comparison",
  ],
  "nhs-band-9-pay-calculator": [
    "nhs-band-8d-pay-calculator",
    "nhs-take-home-pay",
    "nhs-pay-comparison",
    "nhs-scotland-band-9-pay-calculator",
  ],
  "nhs-scotland-band-5-pay-calculator": [
    "nhs-band-5-pay-calculator",
    "nhs-scotland-band-6-pay-calculator",
    "nhs-take-home-pay",
    "nhs-pay-comparison",
  ],
  "nhs-scotland-band-6-pay-calculator": [
    "nhs-band-6-pay-calculator",
    "nhs-scotland-band-5-pay-calculator",
    "nhs-scotland-band-7-pay-calculator",
    "nhs-take-home-pay",
    "nhs-pay-comparison",
  ],
  "nhs-scotland-band-7-pay-calculator": [
    "nhs-band-7-pay-calculator",
    "nhs-scotland-band-6-pay-calculator",
    "nhs-scotland-band-8a-pay-calculator",
    "nhs-take-home-pay",
    "nhs-pay-comparison",
  ],
  "nhs-scotland-band-8a-pay-calculator": [
    "nhs-band-8a-pay-calculator",
    "nhs-scotland-band-7-pay-calculator",
    "nhs-scotland-band-9-pay-calculator",
    "nhs-take-home-pay",
    "nhs-pay-comparison",
  ],
  "nhs-scotland-band-9-pay-calculator": [
    "nhs-band-9-pay-calculator",
    "nhs-scotland-band-8a-pay-calculator",
    "nhs-take-home-pay",
    "nhs-pay-comparison",
  ],
  "nhs-wales-band-5-pay-calculator": [
    "nhs-band-5-pay-calculator",
    "nhs-wales-band-6-pay-calculator",
    "nhs-take-home-pay",
    "nhs-pay-comparison",
  ],
  "nhs-wales-band-6-pay-calculator": [
    "nhs-band-6-pay-calculator",
    "nhs-wales-band-5-pay-calculator",
    "nhs-wales-band-7-pay-calculator",
    "nhs-take-home-pay",
    "nhs-pay-comparison",
  ],
  "nhs-wales-band-7-pay-calculator": [
    "nhs-band-7-pay-calculator",
    "nhs-wales-band-6-pay-calculator",
    "nhs-wales-band-8a-pay-calculator",
    "nhs-take-home-pay",
    "nhs-pay-comparison",
  ],
  "nhs-wales-band-8a-pay-calculator": [
    "nhs-band-8a-pay-calculator",
    "nhs-wales-band-7-pay-calculator",
    "nhs-take-home-pay",
    "nhs-pay-comparison",
  ],
};

// NHS matrix pages share one default set
const nhsRelated = ["nhs-take-home-pay", "nhs-pay-comparison", "nhs-midwife-salary", "take-home-pay-calculator", "national-insurance-calculator"];

// Scotland NHS pages link to their England equivalent and the hub
const scotlandNhsRelated = ["nhs-take-home-pay", "nhs-pay-comparison", "nhs-scotland-band-6-pay-calculator", "take-home-pay-calculator"];
// Wales NHS pages link to their England equivalent and the hub
const walesNhsRelated = ["nhs-take-home-pay", "nhs-pay-comparison", "take-home-pay-calculator", "national-insurance-calculator"];

export function relatedFor(slug: string): string[] {
  if (slug.startsWith("nhs-band-") || slug === "nhs-midwife-salary") {
    return relatedMap[slug] ?? nhsRelated;
  }
  if (slug.startsWith("nhs-scotland-band-")) {
    return relatedMap[slug] ?? scotlandNhsRelated;
  }
  if (slug.startsWith("nhs-wales-band-")) {
    return relatedMap[slug] ?? walesNhsRelated;
  }
  return relatedMap[slug] ?? [];
}
